name: E2E tests banco-api

#gatilhos
on: 
  workflow_dispatch:

jobs:
  tests:

    #[config do SO] (Windows, Linux, Mac, Chrome / Firefox / Edge, ...)
    runs-on: ubuntu-latest

    #[variaveis] (variáveis de ambiente, chaves de acesso as plataformas, etc...)
    env: 
      API_BASE_URL: 'http://localhost:3000'
      PORT: 4000

    #[acoes ou passos]
    steps:
    
      #[projetos] (aplicações, projeto de teste, etc...)
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      - name: Instalação das dependências
        run: npm install
      
      - name: Inciar o servidor de mocks
        run: npm run mock-server & 

      - name: Iniciar o servidor de aplicação
        run: npm run server &

      - name: Executar os testes 
        run:  npx cypress run
        
        
      
      
